travis:
  secure:
    BINSTAR_TOKEN: BJOTa/5Ya0Cmq6C+dGt/NzsFrNynbyFrGCvJiSKOnfn5DOg2aGHkJPn2BcdMihtLA8AqtVRQ80dAtTgQ3LGWxjLpxlh6B0Ve35CMXCL7k4YlQJTXURGbj+l9h/6arC3px7Nza/TgEVldLtVj5oUSqcRwTz1v5cbV+MZFKBc9nZBd1WBxxua5Gy2URvX+wadkeKs7OEIGCTXVGRrTP5STf9I8j5Olop1k+4fe2Xx5tgz8o5nv3XX+3XJiB+QNlz5YOmV4jJ1Vjp1FI/mypnLHExkUctKe/CaItCQm3AsMnfJEOgeIMITf7fakMXShbTooECJxvaiLB3F+YL9SQCfnkr61cXGF9zBpPxLDj9H3AkOLWtA+locH8lOXo36eWIGaYub5iJfUnIVhoQpHgJsOk4QUbWH66QRIGqAqextdrwBkiJ7PY5bQBaj3UHOOyGGey2TSme9DjH+3yDPDGwoBUT2isVDXWzxt0vyJ3eTGKbyZBz5LvJn4Uk6q6riPD/hG8dt+nyRl0S4YJUy/o4taB3H9pQCI+Nr1O6i61eFdO7g4zrdsOXlzBG/FCMazHaJ52QXgAydmi+kccXfhDoGUddefDDoNmedk9F7thu6lnGcT75ZnFYX9ki+Lh1Eulz5HbuVzIkannAa1h5TT5nuyGA2Uyhxd0Q54UYc91jXT6uo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
